name: Appraisal CI Tests

on:
  push:
    branches: "main"
  pull_request:
    branches: "*"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - "6.0"
          - "6.1"
          - "7.0"
          - "7.1"
        ruby:
          - "2.7.6"
          - "3.0.4"
          - "3.1.2"
          - "3.2.2"

    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.gemfile }}.gemfile
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: "Install Ruby ${{ matrix.ruby  }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: |
          bundle install
          bundle exec appraisal install
          bundle exec appraisal rake db:create
          bundle exec appraisal rake db:migrate

      - name: "Run appraisal rspec"
        run: bundle exec appraisal rspec